spring:
  application:
    name: estudiantescmd

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rodrigo73714089ubnt
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect