spring:
  application:
    name: sistemadereservasdesalasdeestudiocmd
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rodrigo73714089ubnt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true